### ISSUE TITLE
Recycling characters isn't triggering MP refund requests

### ISSUE THREAD

**Issue by Jammy2222** [dantarian/bladesdb#100]
Van Cleef was recycled at rank 13.5 having played 2 games and no approvals have been triggered as a result

**Comment by dantarian** [comment]
Can't see what might be causing this - code looks superficially correct. Will investigate.

**Comment by dantarian** [comment]
I can't reproduce this. I ran up an old copy of the database and recycling Van Cleef resulted in a pending MP adjustment as expected.

OTOH, the system is apparently incorrectly refusing to allow recycling of characters over rank 19.9 and is always refunding MP spends on a recycled character at 1CP:1MP, neither of which are in line with how recycling is described in the rules. They're very much edge cases, but I'll get them fixed nonetheless.
