### ISSUE TITLE
Game Page for Game 916 Luna Plena Ululatus Sept 3rd 2017 is missing

### ISSUE THREAD

**Issue by Jammy2222** [dantarian/bladesdb#102]
Error found by following the Page Link in Vertonius' character page

Sat 20 Jul 2019 13:39:40

**Comment by dantarian** [comment]
Looks like a there's a debrief for a user who's since been deleted. I'll have a look to see if I can restore the user record.

**Comment by dantarian** [comment]
I've restored the missing user record - that game should now be visible again.
