### ISSUE TITLE
404 when attempting to access rules pages as a web only member

### ISSUE THREAD

**Issue by AncientSwordRage** [dantarian/bladesdb#103]
Steps to recreate:
 - Navigate to: https://www.bathlarp.co.uk/pages/433
- Click the link 'Player Rules – The Kingdom – Guilds – Druids' ( URL: https://www.bathlarp.co.uk/pages/252 )

Expected:
To be taken to the druid rules page

Actual:
A 404 error page with this text

> 404 Error
> You appear to be trying to do something you shouldn't or access a page that doesn't exist.
> 
> If this isn't the case, please could you log onto the BathLARP Bug Tracker and raise a new Support request, explaining what you did to get this error and copying in the text below.
> 
> Mon 05 Aug 2019 14:05:49

**Comment by xanthipe** [comment]
Closing as not a code issue, just a case of link rot.

However, proofing against link rot around rules pages definitely needs to be addressed in the next version of the system.
