### ISSUE TITLE
'Meeting' link logging me out

### ISSUE THREAD

**Issue by Maisy23** [dantarian/bladesdb#111]
Hey Judith and Warren 
Don't know if I'm doing this right but I found a bug!
I used the 'minutes' link in Doug's 'Comittee Handover Meeting' post on the OOC Announcement page and was logged out seeing a message reading "You need to sign in or sign up before continuing." on the main page.
The login page didn't have my autopopulated details either. Once logged in I was able to go back to the beginning and access the link tho :) 
Thanks
Maisy

**Comment by xanthipe** [comment]
Hi Maisy,

Just to check, do you normally log on via the bathlarp.co.uk domain or do you use the old domain name?

If the latter, it's because Doug's put in an absolute URL rather than a relative one - if the former, let us know so we can investigate more?

Cheers,
Judith

**Comment by Maisy23** [comment]
https://bathlarp.co.uk is the address I log in from
Ta!
Maisy

**Comment by xanthipe** [comment]
Just checked - yep, it's exactly that problem, and this is why I try to get people to use relative links :) `www.domain-name.com` and `domain-name.com` aren't the same address unless some redirects are set up in the background.

If it happens again, you can always copy the link and edit out the 'www.' bit, and we'll add this to our list of things to sort out in the next iteration...

Cheers,
Judith

**Comment by xanthipe** [comment]
Warren has fixed the link to be relative in the post, give it another whirl?

**Comment by Maisy23** [comment]
Yep that's sorted it :) 
Thanks both!
