### ISSUE TITLE
GM List When Creating Events Presents Random Characters Rather Than Names

### ISSUE THREAD

**Issue by Magicaddict** [dantarian/bladesdb#112]
![image](https://user-images.githubusercontent.com/68928506/88728505-d1168600-d129-11ea-8a9d-29765a70601b.png)

When creating events on the event calendar, the available Gamesmasters field does not contain the list of members or GMs, instead showing alphabetically ordered seemingly randome text.  

The effect is replicated when editing an existing unassigned game (there are no assigned games currently with which to test it, thought the August 22nd IC Meal may allow this).

**Comment by xanthipe** [comment]
Ah - not a problem with the website, just a sign that we need to clear out a bot infestation again...

If you start typing names it should hopefully skip to the right part of the alphabet.

**Comment by xanthipe** [comment]
Bot infestation now duly fumigated, will endeavour to keep a better eye on that.
