### ISSUE TITLE
Meeting agendas board dead

### ISSUE THREAD

**Issue by oohfeeshy** [dantarian/bladesdb#125]
https://www.bathlarp.co.uk/boards/19 loading as "We're sorry but something went wrong"

Clicked delete on the existing agenda post and page loaded as above- not sure if cause or coincidence but nothing abnormal is showing on the Manage Message Boards page and I don't know enough about coding to risk poking it more myself

**Comment by dantarian** [comment]
Fix deployed - Agendas board should be working again now!
