### ISSUE TITLE
24HR event not correctly giving Monster credit for GMs

### ISSUE THREAD

**Issue by ElvinDrude** [dantarian/bladesdb#136]
This one may or may not be a bug: The 24HR just gone seems to not give any of the GMs Monstering credits. I can see my ratio is not including it at all. There's been an attempt to fix it, but @xanthipe thinks this may be a bug.

**Comment by dantarian** [comment]
This is because this year's 24 Hour is in the system as a three-day event, and we don't include those in P:M ratios. Not sure you can edit the dates of the event any more as it's in the past, but I can fix it in the database if you'd like?

**Comment by ElvinDrude** [comment]
It would be nice to have it correct, but if it's not something quick and easy don't worry about it :)

**Comment by dantarian** [comment]
Fixed :-)
