### ISSUE TITLE
# based page references don't work for hyperlinks in the event calendar

### ISSUE THREAD

**Issue by Jammy2222** [dantarian/bladesdb#159]
The hyperlink "Guide to a residential Larp":#211 redirected to the event calendar itself in a game brief instead of the actual static page it was supposed to. Full web addresses ("Guide to a residential Larp":https://www.bathlarp.co.uk/pages/211 ) work as expected.

**Comment by xanthipe** [comment]
Did you link in the format "/pages/211"?

**Comment by dantarian** [comment]
Yeah, that's working exactly as I'd expect it to. Use a relative link as @xanthipe suggested.

Links in the form of your first one will try to find a link in the current page with the name "211", and if the don't find it they'll just reload the page. That's the way the internet works, and nothing to do with BladesDB :-)
