### ISSUE TITLE
Incorrect Markup Help Text link on Edit Debrief 

### ISSUE THREAD

**Issue by ElvinDrude** [dantarian/bladesdb#190]
While editing an IC Debrief, I pressed the here in Click [here](http://redcloth.org/textile) to view markup options - and, as I copy-pasted that sentence from the boards, you can see that the link goes somewhere completely unexpected!

**Comment by ElvinDrude** [comment]
Bumping this as it seems http://redcloth.org/textile is now up for sale, which risks potential future issues due to malicious purchase of the site...

**Comment by dantarian** [comment]
Good shout, I'll get this fixed this evening.
