### ISSUE TITLE
New Joiner Bonus applied multiple times to reactivated accounts

### ISSUE THREAD

**Issue by Jammy2222** [dantarian/bladesdb#210]
![Screenshot 2024-02-01 223657](https://github.com/dantarian/bladesdb/assets/43322685/0107854a-fb6a-48b4-9a2c-c22038a03648)

A suspended member who's been unsuspended has had the New Joiner bonus 80 MP twice somehow.

**Comment by dantarian** [comment]
Fix deployed,
