### ISSUE TITLE
New Sales Board Does Not Seem To Count Towards "Unread Messages" Notification

### ISSUE THREAD

**Issue by Magicaddict** [dantarian/bladesdb#218]
![0 Unread in header, 3 unread on new board](https://github.com/dantarian/bladesdb/assets/68928506/0a254767-1724-46fc-829f-7e5b6a348042)

Despite there being unread messages on the sales board, my header states that there are 0 unread messages for me to browse (see attached image). Is the new board missing a flag?

Thank you in advance, 

DougMS

**Comment by dantarian** [comment]
This is working as designed. The "unread" counter in the header bar deliberately excludes any boards you haven't already visited; this is to avoid overwhelming new users with an indication of several thousand unread messages. After you've viewed the board for the first time, any further messages will be indicated in your unread message count.

It's a bit counter-intuitive, though, so we'll see if we can come up with a better approach for the next version - possibly using the user creation date as a way to determine the point from which new messages should be considered to exist.
