### ISSUE TITLE
Bad links on equipment costs page

### ISSUE THREAD

**Issue by oohfeeshy** [dantarian/bladesdb#96]
Internal page links on the Equipment Costs page are trying to go to page 92, but the page is actually 545 so it gets angry.
And because the website told me to, "Sat 27 Oct 2018 19:33:11"

**Comment by xanthipe** [comment]
Internal page formatting issues should be redirected to either the Committee or the Character Refs, depending on whether it's a general page or a rules/setting page.

I'm going to fix it anyway as it's going to annoy me otherwise now I know, but I'm still going to close this issue.
